name: Check for new commit on main

on:
  workflow_dispatch:

jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch "main"
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0
      - name: Code check for commit and update the branch
        run: |
          set -eux
          if [ -z "$(git status --porcelain)" ]; then 
            echo "Working Directory is clean,will now rebase the code"
            git checkout main
            git pull --rebase
            recent_tag=$(git tag --sort=-creatordate | head -n 1)
            echo "The recent tag is : $recent_tag"
            commit_number=$(git rev-list --count HEAD)
            echo "Check if rel- is present in the recent tag"
            if [ -n "$recent_tag" ]; then
                # To check the if the release tag is present with "rel".Format for the release tag : rel-<date>-<release_no>, <date>-<release_no>-<subrelease_no>
                rel=$(echo "${recent_tag}" | awk '/rel-/{print}')  
                echo $rel
                sleep 3s
                if [ -z "$rel" ]; then
                   echo "Tag doesnot have rel-"
                   subrelease_no=$(echo $recent_tag | awk -F"-" '{print $3}')
                   if [ -z "$subrelease_no" ]; then
                      echo "Tag does not have any sub tag number"
                      last_commit_number=$(echo $recent_tag | awk -F"-" '{print $2}')
                      if [ -z "$last_commit_number" ]; then
                        echo "Recent tag doesnot have any commit number"
                        new_tag=$(date '+%Y%m%d')-${commit_number}-0001
                      else
                        new_tag=$(date '+%Y%m%d')-"${commit_number}"-0001
                      fi
                   else
                      last_commit_number=$(echo $recent_tag | awk -F"-" '{print $2}')
                      if [ "$commit_number" -gt "$last_commit_number" ]; then
                        echo "New changes has been found on the branch."
                        new_tag=$(date '+%Y%m%d')-"${commit_number}"-0001
                      else
                        echo "No commit has been commited."
                        new_value=$((subrelease_no+1))
                        new_value_str=$(printf "%04d" "$new_value")
                        echo $new_value_str
                        release_no=$(echo $recent_tag | awk -F"-" '{print $2}')
                        new_tag=$(date '+%Y%m%d')-"${commit_number}"-"${new_value_str}"
                        echo $new_tag
                      fi
                   fi
                else
                   echo "rel- tag is present"
                   commit_number=$(echo "$recent_tag"|awk -F"-" '{print $NF}')
                   new_tag=$(date '+%Y%m%d')-"${commit_number}"-0001
                   echo $new_tag
                fi
              else
                echo "There is no Tag to start."
                new_tag=$(date '+%Y%m%d')-${commit_number}-0001
            fi
            echo $new_tag
            git tag $new_tag main
            git push origin $new_tag
            git pull
            echo "| Number of commits from last Tag |" >> $GITHUB_STEP_SUMMARY
            echo "| ======================================================= |" >> $GITHUB_STEP_SUMMARY
            release_note=$(git log ${recent_tag}..${new_tag} --pretty="%s")
            echo "| $release_note |" >> $GITHUB_STEP_SUMMARY
            echo "| ======================================================= |" >> $GITHUB_STEP_SUMMARY
          else 
             echo "There are uncommited changes available on the branch.Please check and run tag"
             exit 1
          fi
