name: Workflow to create Tags

on:
  push:
  workflow_dispatch:

jobs:
  Create_Tag:
    name: Create_Tag
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%y%m%d')"
      - name: Checkout branch "main"
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: Rebase the main
        env:
          GIT_TOKEN : ${{ secrets.GIT_TOKEN }}
        run: |

          if [ -z "$(git status --porcelain)" ]; then 
            echo "Working Directory is clean,will now rebase the code"
            git checkout main
            git pull --rebase
            recent_tag=$(git tag --sort=-creatordate | head -n 1)
            echo "The recent tag is : $recent_tag"
            echo "Check if rel- is present in the recent tag"
            if [ -n "$recent_tag" ]; then
                rel=$(echo "$recent_tag" | grep -r "rel")
                if [ -n "$rel"]; then
                  echo "rel- tag is present"
                  rel_num=$(echo "$recent_tag"|awk -F"-" '{print $NF}')
                  new_tag=$(date '+%Y%m%d')-${rel_num}-0001
                  echo $new_tag
                  sleep 2s
                else
                  echo "no rel- Tag present"
                  last_value=$(echo "$recent_tag" | awk -F"-" '{print $3}')
                  if [ -n "$last_value" ]; then
                    new_value=$((last_value+1))
                    new_value_str=$(printf "%04d" $new_value)
                    echo $new_value_str
                    new_tag=$(date '+%Y%m%d')-${second_value}-${new_value_str}
                    second_value=$(echo "$recent_tag"|awk -F"-" '{print $2}')
                    echo ${new_tag}
                  else
                    echo "Tag doesnot have any sub tag number"
                    new_tag=$(date '+%Y%m%d')-${second_value}-0001
                    echo $new_tag
                  fi   
                fi
             else
               echo "There is no Tag to start.Please tag it properly"
            fi
          else 
             echo "There are uncommited changes available on the branch.Please check and run tag"
             exit 1
          fi
