name: create automatic Tags workflow 

on:
  workflow_dispatch:

jobs:
  Update-tag:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
      - name: Checkout branch "main"
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0
      - name: Code check for commit and update the branch
        run: |
          set -eux
          if [ -z "$(git status --porcelain)" ]; then 
            echo "Working Directory is clean,will now rebase the code"
            git checkout main
            git pull --rebase
            recent_tag_all=$(curl "https://api.github.com/repos/atulec016/central_call/tags" -H "Authorization:Bearer ${{ secrets.GIT_TOKEN }}")
            echo $recent_tag_all
            commit_number=$(git rev-list --count HEAD)
            # checking if the last tag was in proper format : <date>-Commit_number-<sub_release>
            if [[ $recent_tag_all=~^[0-9]{8}-[0-9]+-[0-9{4}$ ]]; then
              echo "The tag is in format"
            else
              echo "The tag is not in correct format"
            fi   
          else 
             echo "There are uncommited changes available on the branch.Please check and run tag"
             exit 1
          fi
