name: create automatic Tags workflow 

on:
  workflow_call:
   secrets:
      GIT_TOKEN: 
        description: 'GIT PAT token'
        required: true

jobs:
  Update-tag:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
      - name: Checkout branch "main"
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0
      - name: Code check for commit and update the branch
        run: |
          set -eux
          if [ -z "$(git status --porcelain)" ]; then 
            echo "Working Directory is clean,will now rebase the code"
            git checkout main
            git pull --rebase
            recent_tag_all=$(curl "https://api.github.com/repos/$GITHUB_REPOSITORY/tags" -H "Authorization:Bearer ${{ secrets.GIT_TOKEN }}" | jq -r '.[0].name')
            echo $recent_tag_all
            commit_number=$(git rev-list --count HEAD)
            tag_count_on_commit_number=1
            # checking if the last tag was in proper format : <date>-Commit_number-<sub_release>
            if [[ $recent_tag_all =~ ^[0-9]{8}-[0-9]+-[0-9]{4}$ ]]; then
              echo "The tag is in proper format"
              commit_number_on_tag=$(echo $recent_tag_all |awk -F"-" '{print $2}')
              if [ "$commit_number_on_tag" -eq "$commit_number" ]; then
                echo "Commit number is same, increment the sub release number"
                tag_split_count=$(echo $recent_tag_all | awk -F"-" '{print $3}')
                tag_split_count_increment=$((tag_split_count+1))
                tag_count_on_commit_number=$(printf "%04d" "$tag_split_count_increment")
                echo $tag_count_on_commit_number
                new_tag=$(date '+%Y%m%d')-"${commit_number_on_tag}"-"${tag_count_on_commit_number}"
              else
                echo "Commit number on tag is different from the total commit number"
                new_tag=$(date '+%Y%m%d')-"${commit_number}"-000${tag_count_on_commit_number}
              fi
            else
              echo "The tag is not in correct format"
              new_tag=$(date '+%Y%m%d')-"${commit_number}"-000${tag_count_on_commit_number}
            fi
            echo $new_tag
            git tag $new_tag main
            git push origin $new_tag
            git pull
            echo "| Commit_ID(sha Hash) | Commits for ${new_tag} tag |" >> $GITHUB_STEP_SUMMARY
            echo "| :---: | :---: |" >> $GITHUB_STEP_SUMMARY
            release_note=$(git log ${recent_tag_all}..${new_tag} --pretty="%H %s" | while read commit_id commit_msg; do echo "| $commit_id | $commit_msg |" >> $GITHUB_STEP_SUMMARY; done)
          else 
             echo "There are uncommited changes available on the branch.Please check and run tag"
             exit 1
          fi
