on:
  pull_request:
    types:
      - closed

jobs:
  echo-merged-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo Merged Branch
        run: |
          echo "Merged branch: ${{ github.head_ref }}"
