name: test_yaml

on:
  issue_comment:
    types: [created]
      
jobs:
  command_test:
    environment: dev
    runs-on: ubuntu-latest
    outputs:
      app_name: ${{ steps.loop.outputs.app_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Loop and set output
        id: loop
        run: |
          echo "app_name=test" >> $GITHUB_OUTPUT
          set -eux
          output_file="output.txt"
          for i in {1..5}; do
            if [ $(expr $i % 2) == 0 ]; then
              output="Number is even"
            else
              output="Number is odd"
            fi
            echo "$output" >> "$output_file"
            echo "${{ steps.loop.outputs.app_name }}"
          done

      - uses: mshick/add-pr-comment@v2
        if: always()
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message-path: |
             output.txt

      - name: testing
        run: |
          echo "${{ steps.loop.outputs.app_name }}"
          echo "appname=test" >> $GITHUB_ENV
          echo $appname
          echo "${{ vars[format('{0}_cron_job', ((appname))] }}"

          

