name: test_yaml

on: 
  push
      
jobs:
  command_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Loop and set output
        id: loop
        run: |
          output=()
          for i in {1..5}; do
            output+=("Loop iteration $i")
          done
          output_string=$(IFS=, ; echo "${output[*]}")
          echo "::set-output name=loop-output::$output_string"

      - name: Print loop output
        run: |
          loop_output="${{ steps.loop.outputs.loop-output }}"
          IFS=, read -ra output_array <<< "$loop_output"
          for item in "${output_array[@]}"; do
            echo "Loop output: $item"
          done
