name: trigger check Plan

on:
  push

jobs:
  Pipeline_exectuion:
    name: Pipeline_exectuion
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d%m%y')"
      - name: Checkout branch "main"
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: Rebase the main
        run: |
          if [ -z "$(git status --porcelain)" ]; then 
             echo "Working Directory is clean,will now rebase the code"
             git checkout main
             git pull --rebase   
          else 
             echo "There are uncommited changes available on the branch.Please check and run tag"
             exit 1
          fi
      - name: Tag snapshot
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GIT_TOKEN }}
          tag: ${{ steps.date.outputs.date }}
