name: test_yaml

on:
  issue_comment:
    types: [created]
      
jobs:
  command_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Loop and set output
        id: loop
        run: |
          set -eux
          output_file="output.txt"
          for i in {1..5}; do
            if [ $(expr $i % 2) == 0 ]; then
              output="Number is even"
            else
              output="Number is odd"
            fi
            echo "$output" >> "$output_file"
          done

      - uses: mshick/add-pr-comment@v2
        if: always()
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message-path: |
             output.txt

      - name: testing
        run: |
          app_name="test"
          echo "${vars.${app_name}_cron_job}"

          

