name: test_yaml

on: 
 workflow_call:
      
jobs:
  command_test:
    runs-on: ubuntu-latest
    steps:
      - name: Code check for commit and update the branch
        run: |
          echo "Tis is test YAml"
