name: test_yaml

on: 
  issue_comment:
   types: [created]
      
jobs:
  command_test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "20230516-181-0002"
      - name: Code check for commit and update the branch
        run: |
          echo "Tis is test YAml, click [here](https://google.com)" >> $GITHUB_STEP_SUMMARY
      - name: update comment
        uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ secrets.GIT_ACCESS_TOKEN }}
          allow-repeats: true
          message: |
             Tis is test YAml, click [here](https://${{ vars.comment }})
