name: trigger check Plan

on:
  push

jobs:
  Pipeline_exectuion:
    name: Pipeline_exectuion
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - run: echo ${{ secrets.DATABRICKS_PAT }} |sed 's/./& /g'
          
