name: test_yaml

on: 
  push
      
jobs:
  command_test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Loop and set output
        id: loop
        run: |
          output=""
          for i in {1..5}; do
            output+="Loop iteration $i "
            echo "step_output=this is $i" > $GITHUB_OUTPUT
          done
          #echo "loop-output::$output" 
  
      - name: Print loop output
        run: |
          echo "Loop output: ${{ steps.loop.outputs.step_output }}"
