name: test_yaml

on:
  issue_comment:
    types: [created]
      
jobs:
  command_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Loop and set output
        id: loop
        run: |
          set -eux
          output=()
          for i in {1..5}; do
            if [ $(expr $i % 2) == 0 ]; then
              echo "output+=number is even"
            else
              echo "output+=number is odd"
            fi
            output_string=$(IFS=, ; echo "${output[*]}")
            echo "loop-output=$output_string" >> $GITHUB_OUTPUT
          done

      - name: Print loop output
        id: print-loop-output
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const loopOutput = context.payload.workflow_run.jobs['print-loop-output'].steps.loop.outputs['loop-output'];
            const outputArray = loopOutput.split(',');
            const commentBody = outputArray.map(item => `Loop output: ${item}`).join('\n');
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
