name: trigger check Plan

on:
  push

jobs:
  Pipeline_exectuion:
    name: Pipeline_exectuion
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout branch "main"
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: Rebase the main
        run: |
          if [ -z "$(git status --porcelain)" ]; then 
             echo "Working Directory is clean,will now rebase the code"
             git checkout main
             git pull --rebase
             git tag ${{ steps.date.outputs.date }}
             git push --tags   
          else 
             echo "There are uncommited changes available on the branch.Please check and run tag"
          fi
