name: trigger check Plan

on:
  push

jobs:
  trigger_check:
    if: >
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, 'deploy pipeline')
    name: terraform_plan
    uses: atulec016/test_demo/.github/workflows/testing.yml@ag/datab
    secrets:
      DATABRICKS_PAT: ${{ secrets.GIT_ACCESS_TOKEN }}
