name: test_yaml

on:
  issue_comment:
    types: [created]
      
jobs:
  command_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Loop and set output
        id: loop
        run: |
          set -eux
          output=()
          for i in {1..5}; do
            if [ $(expr $i % 2) == 0 ]; then
              output+="Number is even"
            else
              output+="Number is odd"
            fi
            output_string=$(printf "%s\n" "${outputs[@]}")
            #output_variable
            #output_string=$(IFS=, ; echo "${output[*]}")
            echo "output_variable=$output_string" >> $GITHUB_OUTPUT
            #echo "$output_string"
          done
      - name: Print loop output
        run: |
          loop_output="${{ steps.loop.outputs.output_variable }}"
          IFS=$'\n', read -ra output_array <<< "$loop_output"
          for item in "${output_array[@]}"; do
            echo "Loop-output: $item" >> $GITHUB_STEP_SUMMARY
            echo $item >> msg.txt
          done
          
      - name: Comment on issue
        uses: actions/github-script@v3
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const output = `Outputs:\n${{ steps.loop.outputs.output_variable }}`;
              const issueComment = context.issue({ body: output });
              return github.issues.createComment(issueComment);

