on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:
jobs:
  DeployDev:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo Merged Branch
        run: |
          echo "Merged branch: ${{ github.head_ref }}"
