name: trigger check Plan

on:
  push

jobs:
  trigger_check:
    name: terraform_plan
    uses: atulec016/test_demo/.github/workflows/testing.yml@ag/datab
    secrets:
          DATABRICKS_PAT: ${{ secrets.DATABRICKS_PAT }}
